"""Embed the blank-start seed into app/PRAP.html.

A user can now start a plan in the application itself, with no workbook to load. That
needs a starting point, and a genuinely empty one is unusable: with no `Lists` sheet
there are no value lists, so nothing can be chosen from a vocabulary and every typed
value is reported as unrecognised (V-11); with no `Config` there are no thresholds.

So a blank start begins from the reference content of the delivered template - the
value lists and the settings - and nothing else. No projects, no people, no
assignments: those are what the user is there to enter.

Only those two sheets are embedded. The PeriodWeightStandard and RoleFactor grids are
NOT: the application builds them from the value lists it was just seeded with, which
means a company that adds a role or a phase to `Lists` gets that combination in the
grid without anybody regenerating anything. Their numbers start at a placeholder 1.00,
because an invented weight that looks like a company standard is worse than an obvious
placeholder - the application says so on screen, and the note on every row repeats it.

    python tools/build_app_seed.py            # rewrites the SEED block in app/PRAP.html

tools/check_consistency.py verifies the embedded block still matches the template.
"""

import json
import re
import sys
from pathlib import Path

from openpyxl import load_workbook

ROOT = Path(__file__).resolve().parents[1]
APP = ROOT / "app" / "PRAP.html"
TEMPLATE = ROOT / "templates" / "PRAP_SourceData_Template_v1.7.xlsx"
BEGIN = "/* SEED-BEGIN"
END = "/* SEED-END */"


def seed_rows(path=TEMPLATE):
    """The template's Lists and Config sheets, as rows in the sheets' own column order."""
    wb = load_workbook(path, data_only=True)
    out = {}
    for name in ("Lists", "Config"):
        ws = wb[name]
        rows = []
        for raw in ws.iter_rows(min_row=2, values_only=True):
            if all(v is None or v == "" for v in raw):
                continue
            rows.append([None if v == "" else v for v in raw])
        out[name] = rows
    return out


def js_block(rows, template_name):
    def lit(v):
        return "null" if v is None else json.dumps(v, ensure_ascii=False)

    def arr(rs):
        return "[\n" + "".join(f"  [{','.join(lit(v) for v in r)}],\n" for r in rs) + "]"

    return (
        f"{BEGIN} — generated by tools/build_app_seed.py from {template_name}.\n"
        f"   The reference content of a blank start: the value lists and the settings, and\n"
        f"   nothing else. Do not edit by hand — rebuild it, or check_consistency.py fails.\n"
        f"   The weight and role-factor grids are NOT here: blankSheets() builds them from\n"
        f"   these lists, so a company that adds a role gets it without a regeneration. */\n"
        f"const SEED_LISTS = {arr(rows['Lists'])};\n"
        f"const SEED_CONFIG = {arr(rows['Config'])};\n"
        f"{END}"
    )


def main():
    src = APP.read_text(encoding="utf-8")
    block = js_block(seed_rows(), TEMPLATE.name)
    if BEGIN in src:
        i = src.index(BEGIN)
        j = src.index(END) + len(END)
        src = src[:i] + block + src[j:]
    else:
        raise SystemExit(f"app/PRAP.html has no {BEGIN} … {END} block to fill in")
    APP.write_text(src, encoding="utf-8")
    n = sum(len(v) for v in seed_rows().values())
    print(f"embedded {n} seed rows from {TEMPLATE.name} into {APP.relative_to(ROOT)}")


def embedded(src=None):
    """The SEED_LISTS / SEED_CONFIG currently in the application, for the consistency check."""
    src = src or APP.read_text(encoding="utf-8")
    out = {}
    for const, sheet in (("SEED_LISTS", "Lists"), ("SEED_CONFIG", "Config")):
        m = re.search(rf"const {const} = (\[.*?\n\]);", src, re.S)
        if not m:
            return None
        out[sheet] = json.loads(m.group(1).replace(",\n]", "\n]"))
    return out


if __name__ == "__main__":
    sys.exit(main())
