#!/usr/bin/env python3
"""Write the machine-readable rule catalog (docs/spec/rule-catalog.yaml).

The catalog is the artifact CI checks implemented rule modules against. It is
maintained separately from the specification workbook by decision at the Step 1
review; `tools/check_catalog_drift.py` compares the two and fails on mismatch so
that separate maintenance cannot become silent divergence.
"""
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "docs" / "spec" / "rule-catalog.yaml"

# Fields that are contractual: the drift check compares exactly these.
KEYED = ["id", "family", "title", "guideline", "severity", "mode", "status",
         "confidence_base_rate"]


def esc(s: str) -> str:
    """Quote a scalar for YAML without pulling in a YAML dependency."""
    s = str(s).replace("\\", "\\\\").replace('"', '\\"')
    s = s.replace("\n", "\\n")
    return f'"{s}"'


def write_catalog(rules, out=OUT):
    lines = [
        "# TEA rule catalog — machine-readable source for the review engine.",
        "# Generated by tools/build_rule_catalog.py. Maintained alongside",
        "# docs/spec/TEA-SPEC-001_programming-specification.xlsx (Rules sheet).",
        "# CI enforces consistency via tools/check_catalog_drift.py.",
        "# Rule logic confirmed over two review rounds (2026-08-19, 2026-08-21).",
        "# NOT frozen: the pack freezes when Rule_Messages is accepted at the Step 2 gate.",
        "version: 1.2.0",
        "guidelines: [RECIST_1_1, iRECIST]",
        f"rule_count: {len(rules)}",
        "rules:",
    ]
    for r in sorted(rules, key=lambda x: x["id"]):
        lines.append(f"  - id: {r['id']}")
        lines.append(f"    family: {r['family']}")
        lines.append(f"    title: {esc(r['title'])}")
        lines.append(f"    guideline: {esc(r['guideline'])}")
        lines.append(f"    severity: {r['severity']}")
        lines.append(f"    mode: {r['mode']}")
        lines.append(f"    status: {r['status']}")
        lines.append(f"    confidence_base_rate: {r['confidence_base_rate']:.2f}")
        if r.get("required_fields"):
            lines.append(f"    required_fields: {esc(r['required_fields'])}")
        lines.append(f"    intent: {esc(r['intent'])}")
        lines.append("    logic: |")
        for ln in r["logic"].split("\n"):
            lines.append(f"      {ln}")
        lines.append("    messages:")
        for key, field in [("review_point", "msg_review_point"), ("issue", "msg_issue"),
                           ("reason", "msg_reason"), ("query", "msg_query"),
                           ("tips", "msg_tips")]:
            lines.append(f"      {key}: {esc(r[field])}")
    out.write_text("\n".join(lines) + "\n")
    return out


if __name__ == "__main__":
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else REPO / "tools" / "rules.json"
    rules = json.loads(src.read_text())
    p = write_catalog(rules)
    print(f"wrote {p} — {len(rules)} rules")
