"""Embed the blank-start seed into src/core/02_xlsx_write.js.

A user can now start a plan in the application itself, with no workbook to load. That
needs a starting point, and a genuinely empty one is unusable: with no `Lists` sheet
there are no value lists, so nothing can be chosen from a vocabulary and every typed
value is reported as unrecognised (V-11); with no `Config` there are no thresholds.

So a blank start begins from the reference content of the delivered template - the
value lists and the settings - and nothing else. No projects, no people, no
assignments: those are what the user is there to enter.

Only those two sheets are embedded. The PeriodWeightStandard and RoleFactor grids are
NOT: the application builds them from the value lists it was just seeded with, which
means a company that adds a role or a phase to `Lists` gets that combination in the
grid without anybody regenerating anything. Their numbers start at a placeholder 1.00,
because an invented weight that looks like a company standard is worse than an obvious
placeholder - the application says so on screen, and the note on every row repeats it.

    python tools/build_app_seed.py            # rewrites the SEED block in src/core/
    python tools/build_app.py                 # ...and then rebuild the page from src/

The seed goes into the SOURCE, not into the built page. It used to be written straight
into app/PRAP.html, which was correct until N2.1 made that file a build output: from
then on the next `build_app.py` silently discarded it. Nothing noticed, because the
seed had not needed regenerating since - until schema 6 changed the value lists, and
check_consistency caught the seed and the template disagreeing.

tools/check_consistency.py verifies the embedded block still matches the template.
"""

import json
import re
import sys
from pathlib import Path

from openpyxl import load_workbook

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src" / "core" / "02_xlsx_write.js"
TEMPLATE = ROOT / "templates" / "PRAP_SourceData_Template_v1.8.xlsx"
BEGIN = "/* SEED-BEGIN"
END = "/* SEED-END */"


SEEDED = ("Lists", "Config", "PeriodWeightStandard", "RoleFactor")


def seed_rows(path=TEMPLATE):
    """The four sheets a blank plan starts from, in the sheets' own column order.

    Lists and Config are the vocabulary and the thresholds. PeriodWeightStandard and
    RoleFactor are the DEFAULT ASSUMPTIONS, and they are here for the same reason: a
    blank start used to fill both grids with a placeholder 1.00, which makes the
    period weight and the role factor cancel out of the arithmetic altogether. The
    application then produced figures that looked like an answer and were not one.

    Reading them from the template rather than restating them is what makes "the
    application and the workbook hold the same assumptions" a fact rather than a
    promise; check_consistency.py fails if they drift apart.
    """
    wb = load_workbook(path, data_only=True)
    out = {}
    for name in SEEDED:
        ws = wb[name]
        rows = []
        for raw in ws.iter_rows(min_row=2, values_only=True):
            if all(v is None or v == "" for v in raw):
                continue
            rows.append([None if v == "" else v for v in raw])
        out[name] = rows
    return out


def js_block(rows, template_name):
    def lit(v):
        return "null" if v is None else json.dumps(v, ensure_ascii=False)

    def arr(rs):
        return "[\n" + "".join(f"  [{','.join(lit(v) for v in r)}],\n" for r in rs) + "]"

    return (
        f"{BEGIN} — generated by tools/build_app_seed.py from {template_name}.\n"
        f"   The reference content of a blank start: the value lists and the settings, and\n"
        f"   the reference content of a blank start: the value lists, the settings, and the\n"
        f"   DEFAULT ASSUMPTIONS. Do not edit by hand — rebuild it, or check_consistency\n"
        f"   fails. blankSheets() still BUILDS the two grids from the value lists, so a\n"
        f"   company that adds a role gets that combination without a regeneration; these\n"
        f"   rows supply the figure wherever there is one, and 1.00 where there is not. */\n"
        f"const SEED_LISTS = {arr(rows['Lists'])};\n"
        f"const SEED_CONFIG = {arr(rows['Config'])};\n"
        f"const SEED_PWS = {arr(rows['PeriodWeightStandard'])};\n"
        f"const SEED_RF = {arr(rows['RoleFactor'])};\n"
        f"{END}"
    )


def main():
    src = SRC.read_text(encoding="utf-8")
    block = js_block(seed_rows(), TEMPLATE.name)
    if BEGIN in src:
        i = src.index(BEGIN)
        j = src.index(END) + len(END)
        src = src[:i] + block + src[j:]
    else:
        raise SystemExit(f"{SRC.relative_to(ROOT)} has no {BEGIN} … {END} block to fill in")
    SRC.write_text(src, encoding="utf-8")
    n = sum(len(v) for v in seed_rows().values())
    print(f"embedded {n} seed rows from {TEMPLATE.name} into {SRC.relative_to(ROOT)}")
    print("now run: python tools/build_app.py")


def embedded(src=None):
    """The SEED_LISTS / SEED_CONFIG currently in the application, for the consistency
    check. Read from the BUILT page by default, because that is what a user runs - if
    the source were checked instead, a forgotten build_app.py would pass."""
    src = src or (ROOT / "app" / "PRAP.html").read_text(encoding="utf-8")
    out = {}
    for const, sheet in (("SEED_LISTS", "Lists"), ("SEED_CONFIG", "Config"),
                         ("SEED_PWS", "PeriodWeightStandard"), ("SEED_RF", "RoleFactor")):
        m = re.search(rf"const {const} = (\[.*?\n\]);", src, re.S)
        if not m:
            return None
        out[sheet] = json.loads(m.group(1).replace(",\n]", "\n]"))
    return out


if __name__ == "__main__":
    sys.exit(main())
